### PR TITLE
Expand fabpot/goutte Composer version constraint to include 4.x

### PR DESCRIPTION
**Pull request by TravisCarden**
The `fabpot/goutte` project recently cut a new 4.x branch (with an initial [4.0.0](https://github.com/FriendsOfPHP/Goutte/releases/tag/v4.0.0) release) to remove Guzzle. Can we update the dependency to allow the new version?

### CODE REVIEW

**Comment by aik099** [comment]
Would tests still pass with Goutte 4.0.0 version?

Right now Travis CI is totally broken due PHPUnit release/Ubuntu image change on Travis CI so I can't tell.

**Comment by longwave** [comment]
As the Travis builds now look to be fixed, can we get a retest here to see if Goutte 4.x works?

**Comment by aik099** [comment]
@longwave , yes, but to make that happen @TravisCarden needs to rebase his changes on top of `master` branch and that will trigger updated build.

**Comment by TravisCarden** [comment]
Done, @aik099. The Travis Ci build failed for reasons unrelated to this PR--Composer failed to download some dependencies.

**Comment by aik099** [comment]
@TravisCarden , all the failed builds I've checked (e.g. from PHP 7.1 - https://travis-ci.org/github/minkphp/MinkGoutteDriver/jobs/666030191) failed because lots of non-existing methods calls from Goutte 4.0 classes and not because Composer-related failures.

My guess, that this PR needs more work, then just making changes in `composer.json` 😉 .

**Comment by TravisCarden** [comment]
Thanks, @aik099. I won't be able to work on this further. I submitted this pull request in large measure just to see what would happen, and I'm no longer allocated to the task that prompted it. I've configured this PR to allow edits from maintainers if you want to update it. But since I no longer have any stake in the matter, I don't care if you prefer to close it. Thanks! :)

**Comment by Stanislas-Poisson** [comment]
Hello is it possible to ended this PR ? (I'm not enough good to ended this one) I can't use anymote behat with laravel 8 because this is not anymore compatible.

**Comment by aik099** [comment]
> Hello is it possible to ended this PR ? (I'm not enough good to ended this one) I can't use anymote behat with laravel 8 because this is not anymore compatible.

@Stanislas-Poisson , what you mean by ending this PR? According to https://github.com/minkphp/MinkGoutteDriver/pull/80#issuecomment-604680447 comment, PR needs more work, then just changing a `composer.json` file. If you're willing to perform it, then I'll be happy to review the PR.

**Comment by stof** [comment]
Closing in favor of #92

**Pull request closed without merging**
