### PR TITLE
Switch to the Docker-based infrastructure on Travis

### PR DESCRIPTION
**Pull request by stof**
Same than https://github.com/minkphp/MinkSelenium2Driver/pull/210

### CODE REVIEW

**Comment by stof** [comment]
hmm, weird. Why would we get errors in the fixtures for some jobs and not others while they all run them with the PHP 5.6 webserver ?

Looks like I may need another solution

**Comment by aik099** [comment]
Solution is perfect. What creates a problem is Guzzle. If you have Guzzle 5.x or smaller installed, then with your setup (PHP 5.6 as a web server and PHP 5.5 running the tests) all works.

If the Guzzle 6.0.1 (or I guess any 6.x version) is used the cookie related tests start to fail.

I've seen issue/PR recently where somebody attempted to fix something Guzzle 6.x related, but I'm not sure if it was merged to Guzzle/GoutteDriver or it was related.

**Comment by aik099** [comment]
Can't seem to figure out at which step it fails. When driver is asked for `tc` cookie value the value is there, but when `$_COOKIE['tc']` is called in `issue140.php` the `$_COOKIE` array is empty. Seems that Goutte 6.x doesn't properly send `Set-Cookie` headers back on page redirects (just a guess).

**Comment by stof** [comment]
@aik099 there is a bug in Goutte when using custom ports in the URL. See https://github.com/FriendsOfPHP/Goutte/pull/236 for the fix.

**Comment by stof** [comment]
here we go. The Goutte bugfix has been merged.

**Pull request merged**
