### PR TITLE
Support basic auth info in URL

### PR DESCRIPTION
**Pull request by cweiske**
Resolves: https://github.com/minkphp/MinkGoutteDriver/issues/76

### CODE REVIEW

**Comment by aik099** [comment]
Shouldn't this go to https://github.com/minkphp/MinkBrowserKitDriver instead? This driver extends that driver.

**Comment by cweiske** [comment]
I know that `GoutteDriver::prepareUrl()` does not call `parent::prepareUrl()`, so that putting that into the browserkit class would not help.

But I have no idea about how it should be and ask the maintainers for more info about that.

**Comment by aik099** [comment]
I'll start with PR to the https://github.com/minkphp/driver-testsuite to see what is current state of http auth passed in URL support in drivers. The Selenium2 driver would pass, but I'm not sure about others.

Then we can start creating PRs for other drivers.

**Comment by cweiske** [comment]
Test: https://github.com/minkphp/driver-testsuite/pull/15

**Comment by aik099** [comment]
@cweiske , please do a rebase so that the new GitHub Actions build can be used and test added in https://github.com/minkphp/driver-testsuite/pull/15 can be executed.

P.S.
@stof, I'm not seeing a button for returning tests for these repos:

* https://github.com/minkphp/MinkGoutteDriver/actions/workflows/tests.yml
* https://github.com/minkphp/MinkSelenium2Driver/actions/runs/1337066562

For these repos I was able to rerun the builds:

* https://github.com/minkphp/MinkZombieDriver/actions/runs/1490604113
* https://github.com/minkphp/MinkBrowserKitDriver/actions/runs/1459459779

**Comment by cweiske** [comment]
Rebased.

**Comment by aik099** [comment]
Merging, thanks @cweiske .

**Pull request merged**
